Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -36,32 +36,34 @@ jobs:
             for system in "${systems[@]}"; do
               release_id=$(curl -s -m 6 -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/oneclickvirt/lxc_arm_images/releases/tags/$system" | jq -r '.id')
               for file in "${images[@]}"; do
-                  echo "Checking if $file already exists in release..."
-                  existing_asset_id=$(curl -s -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/oneclickvirt/lxc_arm_images/releases/$release_id/assets" | jq -r --arg name "$(basename "$file")" '.[] | select(.name == $name) | .id')
-                  if [ -n "$existing_asset_id" ]; then
-                      echo "Asset $file already exists in release, deleting existing asset..."
-                      delete_response=$(curl -s -X DELETE -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/oneclickvirt/lxc_arm_images/releases/assets/$existing_asset_id")
-                      echo "$delete_response"
-                      if [ $? -eq 0 ] && ! echo "$delete_response" | grep -q "error"; then
-                          echo "Existing asset deleted successfully."
-                      else
-                          echo "Failed to delete existing asset. Skipping file upload..."
-                          rm -rf $file
-                          continue
-                      fi
-                  else
-                      echo "No $file file."
-                  fi
-                  echo "Uploading images"
-                  if [ -f "$file" ] && [ $(stat -c %s "$file") -gt 10485 ]; then
-                      echo "Uploading $file to release..."
-                      curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
-                        -H "Content-Type: application/zip" \
-                        --data-binary @"$file" \
-                        "https://uploads.github.com/repos/oneclickvirt/lxc_arm_images/releases/$release_id/assets?name=$(basename "$file")"
-                      rm -rf $file
-                  else
-                      echo "No $file or less than 10 MB"
+                  if [[ "$file" == *"$system"* ]]; then
+                    echo "Checking if $file already exists in release..."
+                    existing_asset_id=$(curl -s -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/oneclickvirt/lxc_arm_images/releases/$release_id/assets" | jq -r --arg name "$(basename "$file")" '.[] | select(.name == $name) | .id')
+                    if [ -n "$existing_asset_id" ]; then
+                        echo "Asset $file already exists in release, deleting existing asset..."
+                        delete_response=$(curl -s -X DELETE -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/oneclickvirt/lxc_arm_images/releases/assets/$existing_asset_id")
+                        echo "$delete_response"
+                        if [ $? -eq 0 ] && ! echo "$delete_response" | grep -q "error"; then
+                            echo "Existing asset deleted successfully."
+                        else
+                            echo "Failed to delete existing asset. Skipping file upload..."
+                            rm -rf $file
+                            continue
+                        fi
+                    else
+                        echo "No $file file."
+                    fi
+                    echo "Uploading images"
+                    if [ -f "$file" ] && [ $(stat -c %s "$file") -gt 10485 ]; then
+                        echo "Uploading $file to release..."
+                        curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+                          -H "Content-Type: application/zip" \
+                          --data-binary @"$file" \
+                          "https://uploads.github.com/repos/oneclickvirt/lxc_arm_images/releases/$release_id/assets?name=$(basename "$file")"
+                        rm -rf $file
+                    else
+                        echo "No $file or less than 10 MB"
+                    fi
                   fi
               done
             done
